# Generated by Django 4.1.6 on 2023-02-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_newproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproduct',
            old_name='price',
            new_name='price_per_piece',
        ),
        migrations.RemoveField(
            model_name='newproduct',
            name='cost_per_piece',
        ),
    ]
