# Generated by Django 4.1.6 on 2023-02-10 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_rename_price_newproduct_price_per_piece_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='price_per_piece',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
